name: Deploy using SSH

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Use ssh-agent to load SSH key
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Run deployment script (replace with your actual commands)
      - name: Deploy
        run: |
          ssh user@server 'echo "Deploying..."'

