name: Deploy to Server

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - name: Checkout code
        uses: actions/https://github.com/shankar5395/test.git 

      - name: Set up SSH
        uses: webfactory/ssh -i "KEy.pem" ubuntu@ec2-13-127-188-80.ap-south-1.compute.amazonaws.com  
        with:
          ssh-private-key: ${{ git@github.com:shankar5395/test.git }}  

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@ip-172-31-7-178 << 'EOF'
            cd .github/workflows/deploy.yml
            git pull origin main  
            npm install  
            npm run build  
            pm2 restart app  
          EOF
